<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.33" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.33" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="DS.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DS.xsd</DependentUpon>
    </Compile>
    <Compile Update="QL_BanDoAnNhanhDataSet.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>QL_BanDoAnNhanhDataSet.xsd</DependentUpon>
    </Compile>
    <Compile Update="QL_BanDoAnNhanhDataSet1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>QL_BanDoAnNhanhDataSet1.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="DS.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DS.Designer.cs</LastGenOutput>
    </None>
    <None Update="QL_BanDoAnNhanhDataSet.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>QL_BanDoAnNhanhDataSet.Designer.cs</LastGenOutput>
    </None>
    <None Update="QL_BanDoAnNhanhDataSet1.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>QL_BanDoAnNhanhDataSet1.Designer.cs</LastGenOutput>
    </None>
    <None Update="rpBaoCao.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>